import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import './globals.css'
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex justify-between bg-[#383838]">
            <div className="flex items-center py-4 pr-4 gap-12 h-25">
              <Link href="/">
                <img src="/bookbotic_robot.png" alt="BookBotics" className="h-30 w-30" />
              </Link>
              <Show when="signed-in">
                <Link href="/Account" className="text-white rounded-full font-medium text-sm sm:text-base cursor-pointer">Account</Link>
                <Link href="/Dashboard" className="text-white rounded-full font-medium text-sm sm:text-base cursor-pointer">Dashboard</Link>
                <Link href="/AI_Assistant" className="text-white rounded-full font-medium text-sm sm:text-base cursor-pointer">AI Assistant</Link>
              </Show>
            </div>
            <div className="flex items-center p-4 gap-4 h-25">
              <Show when="signed-out">
              <SignInButton forceRedirectUrl="/Dashboard">
                <button className="bg-[#1A6FDB] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton forceRedirectUrl="/Dashboard">
                <button className="bg-[#1A6FDB] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton appearance={{elements: {avatarBox: {width: 40, height: 40}}}} />
            </Show>
            </div>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


